<a href="https://colab.research.google.com/github/kangyeson/AI-Class/blob/main/EX_0914_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/iris.csv")

In [ ]:
X = df.drop("species", axis=1)

y = df["species"]

In [ ]:
X

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm
0                5.1             3.5              1.4             0.2
1                4.9             3.0              1.4             0.2
2                4.7             3.2              1.3             0.2
3                4.6             3.1              1.5             0.2
4                5.0             3.6              1.4             0.2
..               ...             ...              ...             ...
145              6.7             3.0              5.2             2.3
146              6.3             2.5              5.0             1.9
147              6.5             3.0              5.2             2.0
148              6.2             3.4              5.4             2.3
149              5.9             3.0              5.1             1.8

[150 rows x 4 columns]

In [ ]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
model = DecisionTreeClassifier()

model.fit(X_train, y_train)
pred_dt = model.predict(X_test)

In [ ]:
print(classification_report(y_test, pred_dt))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.88      0.93         8
   virginica       0.92      1.00      0.96        12

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30

Random Forest

In [ ]:
random_model = RandomForestClassifier()

random_model.fit(X_train, y_train)
random_pred_dt = random_model.predict(X_test)

In [ ]:
print(classification_report(y_test, random_pred_dt))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.88      0.93         8
   virginica       0.92      1.00      0.96        12

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30

Logistic Regression

In [ ]:
logistic_model = LogisticRegression(max_iter=200)

logistic_model.fit(X_train, y_train)
logistic_pred_dt = logistic_model.predict(X_test)

In [ ]:
print(classification_report(y_test, logistic_pred_dt))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.88      0.93         8
   virginica       0.92      1.00      0.96        12

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30

SVM

In [ ]:
svm_model = SVC()

svm_model.fit(X_train, y_train)
svm_pred_dt = svm_model.predict(X_test)

In [ ]:
print(classification_report(y_test, svm_pred_dt))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.78      0.88      0.82         8
   virginica       0.91      0.83      0.87        12

    accuracy                           0.90        30
   macro avg       0.90      0.90      0.90        30
weighted avg       0.90      0.90      0.90        30

KNN

In [ ]:
knn_model = KNeighborsClassifier()

knn_model.fit(X_train, y_train)
knn_pred_dt = knn_model.predict(X_test)

In [ ]:
print(classification_report(y_test, knn_pred_dt))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.88      0.93         8
   virginica       0.92      1.00      0.96        12

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30